AWSTemplateFormatVersion: 2010-09-09

Description: Create a single DynamoDB table

Resources:
  OrderTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Orders
      TableClass: STANDARD
      AttributeDefinitions:
        - AttributeName: clientId
          AttributeType: S
        - AttributeName: createdAt
          AttributeType: S
      KeySchema:
        - AttributeName: clientId
          KeyType: HASH
        - AttributeName: createdAt
          KeyType: RANGE
      BillingMode: PROVISIONED
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
