AWSTemplateFormatVersion: 2010-09-09

Description: This template configures an EC2 instance to use for demonstration of IMDS V2
Parameters:
  KeyName:
    Type: String
    Description: KeyName of existing EC2 KeyPair
    Default: DevSimpleKey

Resources:
  Ec2Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: SimpleEc2Role
      Description: Role for EC2 instance
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess

  Ec2Profile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: SimpleEc2Profile
      Roles:
        - !Ref Ec2Role

  WebSecGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: WebSecGroup
      GroupDescription: Security group for ECS instance
      SecurityGroupIngress:
        - Description: Allow SSH access from anywhere
          IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      KeyName: !Ref KeyName
      ImageId: ami-04ba8620fc44e2264 # Amazon Linux 2023 AMI 64-bit  (x86),  for eu-west-2
      IamInstanceProfile: !Ref Ec2Profile
      SecurityGroupIds:
        - !GetAtt WebSecGroup.GroupId
      Tags:
        - Key: Name
          Value: SimpleInstance

Outputs:
  PublicIp:
    Description: Public IP address for the EC2 instance
    Value: !GetAtt Instance.PublicIp
