AWSTemplateFormatVersion: 2010-09-09

Description: Configure Canary Deployment for API Gateway Stage

Resources:
  Version1Alias:
    Type: AWS::Lambda::Alias
    Properties:
      Name: prod
      Description: Alias for Version 1 of the Lambda
      FunctionName: !ImportValue Lambda-FunctionName
      FunctionVersion: 1

  LatestVersionAlias:
    Type: AWS::Lambda::Alias
    Properties:
      Name: v2
      Description: Alias for latest version of the Lambda
      FunctionName: !ImportValue Lambda-FunctionName
      FunctionVersion: $LATEST

  ApiGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: SimpleApi
      EndpointConfiguration:
        Types: [REGIONAL] # REGIONAL | EDGE  | PRIVATE

  MainMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: GET
      ResourceId: !GetAtt ApiGateway.RootResourceId
      RestApiId: !Ref ApiGateway
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub [
            "arn:aws:apigateway:${Region}:lambda:path/2015-03-31/functions/${FunctionArn}:${!stageVariables.lambdaAlias}/invocations", # Use escape syntax ! to prevent CloudFormation trying to substitute stage variable stageVariables.lambdaAlias
            {
              FunctionArn: !ImportValue Lambda-FunctionArn,
              Region: !Ref AWS::Region,
            },
          ]

  LambdaVersion1Permission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref Version1Alias
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiGateway}/*/*/*

  LatestVersionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref LatestVersionAlias
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiGateway}/*/*/*

  Deployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn: MainMethod
    Properties:
      RestApiId: !Ref ApiGateway
      StageName: placeholder # real stage set below

  ProdStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      StageName: prod
      RestApiId: !Ref ApiGateway
      DeploymentId: !Ref Deployment
      Variables:
        lambdaAlias: prod
      CanarySetting:
        DeploymentId: !Ref Deployment
        PercentTraffic: 50 # In production it is usally meant to be small like 10%
        UseStageCache: false
        StageVariableOverrides:
          lambdaAlias: v2

Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/prod/
  DeploymentId:
    Description: Deployment Id
    Value: !Ref Deployment
