AWSTemplateFormatVersion: 2010-09-09

Description: Configure DynamoDB table with a Resource Based Policy

Parameters:
  CrossAccountId:
    Type: Number
    Description: AWS AccountId for another account

Resources:
  SimpleTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: SimpleTable
      BillingMode: PAYPERREQUEST
      AttributeDefinitions:
        - AttributeName: UserId
          AttributeType: S
      KeySchema:
        - AttributeName: UserId
          KeyType: HASH
      ResourcePolicy:
        Version: 2012-10-17
        Statement:
          - Sid: AllowCrossAccountAccess
            Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${CrossAccountId}:root"
            Action:
              - dynamodb:PutItem
              - dynamodb:GetItem
            Resource: "*"
