AWSTemplateFormatVersion: 2010-09-09

Description: Create a secret in AWS Secrets Manager

Parameters:
  Password:
    Type: String
    Description: The password for the database user
    NoEcho: true

Resources:
  SimpleSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: /prod/db-secret
      Description: A simple secret for demonstration purposes
      SecretString:
        Fn::Sub: |
          {
            "DB_USERNAME": "admin",
            "DB_PASSWORD": "${Password}"
          }
      Tags:
        - Key: Environment
          Value: Development
