AWSTemplateFormatVersion: 2010-09-09

Description: Create a custom resource

Parameters:
  S3Bucket:
    Type: String
    Description: Existing S3 bucket holding the Lambda code
    Default: chucks-workspace-storage
  S3Key:
    Type: String
    Description: Object key for the Lambda code
    Default: artifacts/custom-3007.zip

Resources:
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: CustomLambdaPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: SsmParameterPutDelete
                Effect: Allow
                Action:
                  - ssm:PutParameter
                  - ssm:DeleteParameter
                Resource: "*"

  LambdaFunc:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: SimpleFunc
      Description: Lambda function that create custom resources
      Runtime: python3.9
      Handler: lambda.handler
      Role: !GetAtt LambdaRole.Arn
      Code:
        S3Bucket: !Ref S3Bucket
        S3Key: !Ref S3Key

  CustomResource:
    Type: Custom::RandomSsmParameter
    Properties:
      ServiceToken: !GetAtt LambdaFunc.Arn
