Resources:
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: NginxFamily
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - EC2
      Cpu: "256"
      Memory: "512"
      ContainerDefinitions:
        - Name: NginxContainer
          Image: nginx:latest
          PortMappings:
            - ContainerPort: 80
              Protocol: tcp
