AWSTemplateFormatVersion: 2010-09-09

Description: Using Parameter Store with Lambda

Parameters:
  S3Bucket:
    Type: String
    Description: S3 bucket where the Lambda code lives
    Default: chucks-workspace-storage
  S3Key:
    Type: String
    Description: The S3 Object key for the Lambda Hander Code
    Default: artifacts/0.0.1/lambda-0808.zip

Resources:
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: LambdaPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: AllowParameterGet
                Effect: Allow
                Action:
                  - ssm:GetParameters
                  - ssm:GetParametersByPath
                Resource: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/myapp/*
              - Sid: AllowKMSDecrypt # This is useful when any of the Parameter is of type SecureString
                Effect: Allow
                Action: kms:Decrypt
                Resource: "*"

  LambdaFunc:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: ParameterLambda
      Runtime: python3.9
      Role: !GetAtt LambdaRole.Arn
      Handler: lambda.handler
      Environment:
        Variables:
          ENV: dev
      Code:
        S3Bucket: !Ref S3Bucket
        S3Key: !Ref S3Key
