AWSTemplateFormatVersion: 2010-09-09

Description: Elastic Beanstalk Multi-Container Application which uses ECS under the hood

Parameters:
  S3Bucket:
    Type: String
    Description: S3 bucket where a zipped package containing the Dockerrun.aws.json is stored
    Default: chucks-workspace-storage
  PackageS3Key:
    Type: String
    Description: S3 key for the zipped package containing the Dockerrun.aws.json
    Default: artifacts/multi-container-config.zip
  SolutionStackName:
    Type: String
    Description: The soluton stack name to use
    Default: "64bit Amazon Linux 2023 v4.2.4 running ECS"
    # aws elasticbeanstalk list-available-solution-stacks --query "SolutionStacks"
    # Search for "running ECS"
  CNamePrefix:
    Type: String
    Description: A prefix for the Environment DNS name
    Default: simple-app
  KeyPairName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instances
    Default: DevSimpleKey

Resources:
  InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSElasticBeanstalkWebTier
        # - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        - arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceforEC2Role
        - arn:aws:iam::aws:policy/AWSElasticBeanstalkMulticontainerDocker

  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref InstanceRole

  Application:
    Type: AWS::ElasticBeanstalk::Application
    Properties:
      ApplicationName: SimpleNestApp
      Description: Multi-container Docker app using public DockerHub images

  AppVersion:
    Type: AWS::ElasticBeanstalk::ApplicationVersion
    Properties:
      ApplicationName: !Ref Application
      Description: Initial version
      SourceBundle:
        S3Bucket: !Ref S3Bucket
        S3Key: !Ref PackageS3Key

  EBInstanceSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: EBInstanceSG
      GroupDescription: Enable SSH access and MySQL access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          CidrIp: 0.0.0.0/0

  Environment:
    Type: AWS::ElasticBeanstalk::Environment
    Properties:
      EnvironmentName: !Sub "${AWS::StackName}Env"
      ApplicationName: !Ref Application
      SolutionStackName: !Ref SolutionStackName
      VersionLabel: !Ref AppVersion
      CNAMEPrefix: !Ref CNamePrefix
      OptionSettings:
        - Namespace: aws:autoscaling:launchconfiguration
          OptionName: InstanceType
          Value: t2.micro
        - Namespace: aws:autoscaling:launchconfiguration
          OptionName: IamInstanceProfile
          Value: !Ref InstanceProfile
        - Namespace: aws:autoscaling:launchconfiguration
          OptionName: EC2KeyName
          Value: !Ref KeyPairName
        - Namespace: aws:autoscaling:launchconfiguration
          OptionName: SecurityGroups
          Value: !Ref EBInstanceSG

Outputs:
  EnvironmentUrl:
    Description: Endpoint URL of the Elastic Beanstalk environment
    Value: !Sub "http://${CNamePrefix}.${AWS::Region}.elasticbeanstalk.com"
  EndpointUrl:
    Description: "Elastic Beanstalk Environment URL"
    Value: !GetAtt Environment.EndpointURL
